### ISSUE TITLE
#issue001. Category 설계에 관련된 질문 건입니다.

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/new_blog#15]
Category를 설계하는 과정에서 계층형 구조로 Category를 설계하게 되면 union쿼리가 불가피하게 나가야 하기 때문에 성능 이슈가 발생할 수 있는데 이 때 해결 방법에 대해 토론해보면 좋을 것 같아요

**Comment by jojiapp** [comment]
전체 조회가 아니라 특정 회원의 카테고리만 계층적으로 조회하면 된다면

셀프조인으로 설계한 다음
조회 시, 특정 회원의 카테고리를 전체 로드해서 계층구조로 만드는 작업을 애플리케이션 단에서 하면 되지 않을까 싶습니다.

**Comment by ilgolf** [comment]
흠 그게 좋겠네요 저도 관련 글들을 찾아봤는데 그 이상 좋은 점은 찾지 못했습니다. 
다만 카테고리를 이용해 게시글을 조회하기 보단 추후 태그를 만들어 보는게 좋을 것 같은데 의견이 궁급합니다.

**Comment by jojiapp** [comment]
저도 동의합니다. 카테고리는 개인의 분류로서 사용하고 조회는 태그가 더 좋은거 같습니다.
