### ISSUE TITLE
#issue002. 게시판 조회 시 조회가 일어날 때 마다 counting은 되는데 조회 시 viewCount가 변경되지 않습니다.

### ISSUE THREAD

**Issue by ilgolf** [ilgolf/new_blog#20]
원인은 영속성 컨텍스트에 존재하는 1차 캐시에서 값을 조회하기 때문에 벌크 연산을 하게 되면 조회가 안되는 건데요 각자 해결 방법에 대해 고민해보시면 좋을 것 같습니다.

p.s 동시성 이슈를 반드시 같이 고려하시기 바랍니다.

**Comment by jojiapp** [comment]
BoardCount 조회 시, Board가 같이 조회되므로 벌크연산을 하면 영속성 컨텍스트에 반영이 안되는거 같습니다.

BoardCount와 Board의 연관관계를 Lazy로 변경하고 조회 수 벌크연산 후 Board를 조회하는것이 맞는거 같습니다.

추가로 더티체킹으로 해결하면 조회수 동시성 이슈가 생길수도 있을거같습니다.
